// front/components/OptionsPanel.vue
<script setup lang="ts">
import type { TranslatorKey } from "~/types";
import { validTranslators } from "~/types";
import {
  languageOptions,
  detectionResolutions,
  textDetectorOptions,
  inpaintingSizes,
  inpainterOptions,
  colorizerOptions,
} from "~/config";

const detectionResolution = defineModel<string>("detectionResolution", { required: true });
const textDetector = defineModel<string>("textDetector", { required: true });
const renderTextDirection = defineModel<string>("renderTextDirection", { required: true });
const translator = defineModel<TranslatorKey>("translator", { required: true });
const targetLanguage = defineModel<string>("targetLanguage", { required: true });
const inpaintingSize = defineModel<string>("inpaintingSize", { required: true });
const customUnclipRatio = defineModel<number>("customUnclipRatio", { required: true });
const customBoxThreshold = defineModel<number>("customBoxThreshold", { required: true });
const maskDilationOffset = defineModel<number>("maskDilationOffset", { required: true });
const inpainter = defineModel<string>("inpainter", { required: true });
const colorizer = defineModel<string>("colorizer", { required: true });

const detectionResolutionOptions = detectionResolutions.map((res) => ({
  label: `${res}px`,
  value: String(res),
}));

const inpaintingSizeOptions = inpaintingSizes.map((size) => ({
  label: `${size}px`,
  value: String(size),
}));

const translatorOptions = validTranslators.map((key) => ({
  value: key,
  label: getTranslatorName(key),
}));

const renderDirectionOptions = [
  { value: "auto", label: "Auto" },
  { value: "horizontal", label: "Horizontal" },
  { value: "vertical", label: "Vertical" },
];
</script>

<template>
  <div>
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
      <LabeledSelect
        id="detectionResolution"
        label="Detection Resolution"
        title="Detection resolution"
        v-model="detectionResolution"
        :options="detectionResolutionOptions"
      />

      <LabeledSelect
        id="textDetector"
        label="Text Detector"
        title="Text detector"
        v-model="textDetector"
        :options="textDetectorOptions"
      />

      <LabeledSelect
        id="renderTextDirection"
        label="Render Direction"
        title="Render text orientation"
        v-model="renderTextDirection"
        :options="renderDirectionOptions"
      />

      <LabeledSelect
        id="translator"
        label="Translator"
        title="Translator"
        v-model="translator"
        :options="translatorOptions"
      />

      <LabeledSelect
        id="targetLanguage"
        label="Target Language"
        title="Target language"
        v-model="targetLanguage"
        :options="languageOptions"
      />
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4 mt-4">
      <LabeledSelect
        id="inpaintingSize"
        label="Inpainting Size"
        title="Inpainting size"
        v-model="inpaintingSize"
        :options="inpaintingSizeOptions"
      />

      <LabeledInput
        id="unclipRatio"
        label="Unclip Ratio"
        title="Unclip ratio"
        :step="0.01"
        v-model="customUnclipRatio"
      />

      <LabeledInput
        id="boxThreshold"
        label="Box Threshold"
        title="Box threshold"
        :step="0.01"
        v-model="customBoxThreshold"
      />

      <LabeledInput
        id="maskDilationOffset"
        label="Mask Dilation Offset"
        title="Mask dilation offset"
        :step="1"
        v-model="maskDilationOffset"
      />

      <LabeledSelect
        id="inpainter"
        label="Inpainter"
        title="Inpainter"
        v-model="inpainter"
        :options="inpainterOptions"
      />

      <LabeledSelect
        id="colorizer"
        label="Colorization"
        title="Colorize the page before translation is rendered"
        v-model="colorizer"
        :options="colorizerOptions"
      />
    </div>
  </div>
</template>

// front/app/components/OptionsPanel.tsx
import React from "react";
import type { TranslatorKey } from "@/types";
import { validTranslators } from "@/types";
import { getTranslatorName } from "@/utils/getTranslatorName";
import {
  languageOptions,
  detectionResolutions,
  textDetectorOptions,
  inpaintingSizes,
  inpainterOptions,
  colorizerOptions,
} from "@/config";
import { LabeledInput } from "@/components/LabeledInput";
import { LabeledSelect } from "@/components/LabeledSelect";

type Props = {
  detectionResolution: string;
  textDetector: string;
  renderTextDirection: string;
  translator: TranslatorKey;
  targetLanguage: string;
  inpaintingSize: string;
  customUnclipRatio: number;
  customBoxThreshold: number;
  maskDilationOffset: number;
  inpainter: string;
  colorizer: string;

  setDetectionResolution: (val: string) => void;
  setTextDetector: (val: string) => void;
  setRenderTextDirection: (val: string) => void;
  setTranslator: (val: TranslatorKey) => void;
  setTargetLanguage: (val: string) => void;
  setInpaintingSize: (val: string) => void;
  setCustomUnclipRatio: (val: number) => void;
  setCustomBoxThreshold: (val: number) => void;
  setMaskDilationOffset: (val: number) => void;
  setInpainter: (val: string) => void;
  setColorizer: (val: string) => void;
};

export const OptionsPanel: React.FC<Props> = ({
  detectionResolution,
  textDetector,
  renderTextDirection,
  translator,
  targetLanguage,
  inpaintingSize,
  customUnclipRatio,
  customBoxThreshold,
  maskDilationOffset,
  inpainter,
  colorizer,
  setDetectionResolution,
  setTextDetector,
  setRenderTextDirection,
  setTranslator,
  setTargetLanguage,
  setInpaintingSize,
  setCustomUnclipRatio,
  setCustomBoxThreshold,
  setMaskDilationOffset,
  setInpainter,
  setColorizer,
}) => {
  return (
    <>
      {/* 1段目のセクション */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
        {/* Detection Resolution */}
        <LabeledSelect
          id="detectionResolution"
          label="Detection Resolution"
          icon="carbon:fit-to-screen"
          title="Detection resolution"
          value={detectionResolution}
          onChange={setDetectionResolution}
          options={detectionResolutions.map((res) => ({
            label: `${res}px`,
            value: String(res),
          }))}
        />

        {/* Text Detector */}
        <LabeledSelect
          id="textDetector"
          label="Text Detector"
          icon="carbon:search-locate"
          title="Text detector"
          value={textDetector}
          onChange={setTextDetector}
          options={textDetectorOptions}
        />

        {/* Render text direction */}
        <LabeledSelect
          id="renderTextDirection"
          label="Render Direction"
          icon="carbon:text-align-left"
          title="Render text orientation"
          value={renderTextDirection}
          onChange={setRenderTextDirection}
          options={[
            { value: "auto", label: "Auto" },
            { value: "horizontal", label: "Horizontal" },
            { value: "vertical", label: "Vertical" },
          ]}
        />

        {/* Translator */}
        <LabeledSelect
          id="translator"
          label="Translator"
          icon="carbon:operations-record"
          title="Translator"
          value={translator}
          onChange={(val) => setTranslator(val as TranslatorKey)}
          options={validTranslators.map((key) => ({
            value: key,
            label: getTranslatorName(key),
          }))}
        />

        {/* Target Language */}
        <LabeledSelect
          id="targetLanguage"
          label="Target Language"
          icon="carbon:language"
          title="Target language"
          value={targetLanguage}
          onChange={setTargetLanguage}
          options={languageOptions}
        />
      </div>

      {/* 2段目のセクション */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4 mt-4">
        {/* Inpainting Size */}
        <LabeledSelect
          id="inpaintingSize"
          label="Inpainting Size"
          icon="carbon:paint-brush"
          title="Inpainting size"
          value={inpaintingSize}
          onChange={setInpaintingSize}
          options={inpaintingSizes.map((size) => ({
            label: `${size}px`,
            value: String(size),
          }))}
        />

        {/* Unclip Ratio */}
        <LabeledInput
          id="unclipRatio"
          label="Unclip Ratio"
          icon="weui:max-window-filled"
          title="Unclip ratio"
          step={0.01}
          value={customUnclipRatio}
          onChange={setCustomUnclipRatio}
        />

        {/* Box Threshold */}
        <LabeledInput
          id="boxThreshold"
          label="Box Threshold"
          icon="weui:photo-wall-outlined"
          title="Box threshold"
          step={0.01}
          value={customBoxThreshold}
          onChange={setCustomBoxThreshold}
        />

        {/* Mask Dilation Offset */}
        <LabeledInput
          id="maskDilationOffset"
          label="Mask Dilation Offset"
          icon="material-symbols:adjust-outline"
          title="Mask dilation offset"
          step={1}
          value={maskDilationOffset}
          onChange={setMaskDilationOffset}
        />

        {/* Inpainter */}
        <LabeledSelect
          id="inpainter"
          label="Inpainter"
          icon="carbon:paint-brush"
          title="Inpainter"
          value={inpainter}
          onChange={setInpainter}
          options={inpainterOptions}
        />

        {/* Colorizer */}
        <LabeledSelect
          id="colorizer"
          label="Colorization"
          icon="carbon:color-palette"
          title="Colorize the page before translation is rendered"
          value={colorizer}
          onChange={setColorizer}
          options={colorizerOptions}
        />
      </div>
    </>
  );
};
